export {default as Introduction} from "@/components/introductionMUi";
export {default as UIDesign} from "./UXdesign"
export {default as DemoMakeStyles} from "./makeStyles";
export {default as Hooks} from "./makeStyles";
export {default as Typo} from "./Typography";
export {default as ThemeDemo} from "./Theme";
export {default as PaperDemo} from "./paper";
export {default as NavBar} from "./NavBar/NavBar";
export {default as DarkMode} from "./DarkMode/index";
export {default as Templates} from "./templates";
export {default as GridLayout} from "./GridLayout";
export {default as CardDemo} from "./card";
export {default as TableDemo} from "./Table";
export {default as PokemonPage} from "./Pokemon";
export {default as Pokemon} from "./Pokemon/Pokemon";
export {default as PokemonNotFound} from "./Pokemon/NotFound";